# Credit for code: https://github.com/mkdocs/mkdocs/discussions/2369#discussioncomment-625475
name: Build MkDocs site

on:
  push:
    branches:
      - main
    paths:
      - "mkdocs/**/**.md"
      - "mkdocs/mkdocs.yml"
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install mkdocs
      - name: Publish docs
        run: |
          git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
          python mkdocs/mkdocs-config/setup.py develop
          mkdocs gh-deploy --config-file mkdocs/mkdocs.yml
